# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T784KCrpaCjW2Ul-imrlocORFlPOtvaD
"""

!pip install openai

import os
import openai

openai.api_key = "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"

prompt = input("User Prompt: ")

messages = [
    {"role": "system", "content": ""},
    {"role": "user", "content": prompt},
    {"role": "assistant", "content": ""}
]

completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=messages
)

response = completion['choices'][0]['message']
print("Assistant's response:")
print(response['content']) 

response = completion['choices'][0]['message']
assistant_content_tokens = len(response['content'])


system_tokens = len("system")
assistant_tokens = len("assistant")
user_tokens = len("user")

response = completion['choices'][0]['message']
assistant_content_tokens = len(response['content'])

system_total_tokens = system_tokens + len(messages[0]['content'])
user_total_tokens = user_tokens + len(messages[1]['content'])
assistant_total_tokens = assistant_tokens + assistant_content_tokens

total_tokens = system_total_tokens + user_total_tokens + assistant_total_tokens

cost_per_1000_tokens = 0.002 / 1000 
cost = cost_per_1000_tokens * total_tokens

print(f"System Tokens: {system_total_tokens}")
print(f"User Tokens: {user_total_tokens}")
print(f"Assistant Tokens: {assistant_total_tokens}")
print(f"Total Tokens: {total_tokens}")
print(f"Cost: ${cost:.4f}")